### ISSUE TITLE
question on zig-fn.zig stack usage

### ISSUE THREAD

**Issue by nurpax** [natecraddock/ziglua#114]
https://github.com/natecraddock/ziglua/blob/a3e518f950a89c24ca1b827d7513411acfb230f8/examples/zig-fn.zig#L46

Shouldn't the stack index be -1 instead of 1 here to get the return value of the previously called function?  I think if you had something else in the stack before the pcall, `lua.toInteger(1)` would return something else than the result of the adder function?

It now looks like it works only by accident, and might be a misleading example.  Unless I'm completely misunderstanding how return values get passed.

**Comment by natecraddock** [comment]
Oh good catch, thank you. In this case index 1 does work because there is nothing else on the stack, but it would be best to give an example of code that is more reliable and generally useful

I also see a few other misleading comments in this file (note about stable pointers from when it required an allocator pointer), so I'll clean it up soon.
