### ISSUE TITLE
Rename error.Fail to error.LuaError

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/ziglua#16]
Also prefix the other errors with Lua

Not sure yet, but it seems that would be a good way to namespace things?

**Comment by nurpax** [comment]
Just throwing this out here, I'm not sure I know what is the right answer to this.

But would it make sense to return `std.mem.Allocator.Error.OutOfMemory` directly from std.mem.Allocator failures instead of translating to `error.Memory`?  I don't have a motivating example case for this, but it feels like it might harmonize error handling code if Ziglua doesn't define another error for OOM.

**Comment by natecraddock** [comment]
I agree, reusing the OutOfMemory error would make sense

**Comment by VisenDev** [comment]
error.LuaError is a more descriptive than error.Fail

Just getting "error: fail" can be a little annoying
