### ISSUE TITLE
Document releases

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/ziglua#23]
* releases tied to Zig versions
* main branch tracks Zig master

**Comment by nurpax** [comment]
Paging in @robbielyman and @natecraddock 

BTW: I've decided to stick to zig 0.14 in my own projects and started thinking again what's the best way to track zig versions.

Like where should "lua_wrapper" develop new features?  In main using the latest zig?  This could potentially suck if more and more people are going for 0.14 now that the language is starting to shape up so that official releases are pretty usable as is.

Well, not that I'm actually so much in need of new features in lua_wrapper, but at least one area where a lot of work could go in is all the parts touching Luajit.  If that's done in Main, would the features be usable for those who use 0.14?
